# Generated by Django 4.0 on 2024-11-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedulemodel_memo_schedulemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
