# Generated by Django 4.0 on 2024-11-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedulemodel_is_completed_schedulemodel_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='points',
        ),
    ]
